default: &default
  adapter: mysql2
  username: ghost
  password: milana
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: report_api_development

test:
  <<: *default
  database: report_api_test

production:
  <<: *default
  database: report_api_production
